### ISSUE TITLE
Use draw.io in $PATH instead of absolute location

### ISSUE THREAD

**Issue by Daltz333** [modelmat/sphinxcontrib-drawio#23]
Additionally, have the location configurable

**Comment by Modelmat** [comment]
Isn't the location already configurable through `drawio_binary_path` in the sphinx conf?
For local development, there is an (admittedly undocumented outside of the test source code) the ability to create a .gitignore'd config file which gets filled into the tests.

**Comment by Modelmat** [comment]
Oh, I just saw #11 and now and get what this means.
I'm not sure if this is a good idea - I'll have to see if draw.io adds itself to $PATH by default.

**Comment by ItayZiv** [comment]
It does not, but its the only sustainable way to have be able to build draw.io on a big project with different machines having different project structures.
But setting the absoule location to the executable name would have the same effect, so this can just be documented (with a note in readme), and that should be enough.

**Comment by brechtm** [comment]
Installing drawio on Ubuntu from .deb places the drawio executable inside _/usr/bin_ which is on the PATH. This is also the default for practically every application installed on *nix systems, so I think we should first look for drawio on the PATH, and only if that fails we can check some common paths there drawio can be typically found. The latter is mostly necessary for Windows and macOS.

If `drawio_binary_path` is set, we should of course call that drawio instead of the one on the PATH.
