### ISSUE TITLE
Request: add options for :name: for sphinx linking and :caption: to label each drawing

### ISSUE THREAD

**Issue by binarylandscapes** [Modelmat/sphinxcontrib-drawio#28]

**Comment by ItayZiv** [comment]
What exactly would this do?

**Comment by Modelmat** [comment]
Would `:name:` set an id attr to the image, so that you can do `#image-name`.
The caption would just be a <div> below the image I would think.

**Comment by binarylandscapes** [comment]
So I am using another extension as the basis for the request. http://blockdiag.com/en/blockdiag/sphinxcontrib.html#directive

caption : text
The caption of the diagram.

name : text
Set a names attribute value on the diagram-image element. This allows hyperlink references to the diagram using text as reference name.

**Comment by brechtm** [comment]
I've done some experiments on implementing this. My approach is to inherit from Sphinx's _Figure_ directive class and simply grab the drawio image's filename from it, export it to the specified format and replace the image URI with the path to the exported file. This has the advantage that the drawio figure directive will behave exactly like a regular figure (e.g. numbering). Further, it eliminates the need for the current builder-specific code which duplicates docutils/Sphinx code. The directive would automatically support all of the figure directive's options, and we can add extra drawio-specific options to control export of the image.

To extend these advantages to the existing drawio directive, I would like it to inherit from docutil's _Image_ directive class. However, this would break backward compatibility, since some of the _drawio_ directive's options conflict with those of _image_ and _figure_. I suggest introducing _drawio-image_ and _drawio-figure_ directives and deprecating _drawio_.

Welcoming your feedback! I'll try to submit a PR with my current implementation before I leave on a vacation at the end of this week.

**Comment by ItayZiv** [comment]
If anything you can register directives under a domain (I’ll check the details when I get to a computer), this would result in drawio:image (iirc).
Regardless, after some time with both around we can probably bump version and remove the old one and rename everything (while keeping the old name and the normal name)

**Comment by brechtm** [comment]
> If anything you can register directives under a domain (I’ll check the details when I get to a computer), this would result in drawio:image (iirc).

Thanks, I didn't know about that. I'll look into it.

**Comment by brechtm** [comment]
> If anything you can register directives under a domain (I’ll check the details when I get to a computer), this would result in drawio:image (iirc).

Reading the [description of domains](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html?highlight=domains#domains) in the Sphinx documentation, they don't seem like a great fit for this use case. I'm thinking sticking with `drawio-image` and `drawio-figure` is better.

> Regardless, after some time with both around we can probably bump version and remove the old one and rename everything (while keeping the old name and the normal name)

Looking further into this, I feel that it would be too much work to try to reuse code among the code for the legacy `drawio` directive and the new image/figure directives (making sure it still works as before). I'm taking the pragmatic approach of copying the legacy code to `olddrawio.py` and use it as is. This code can eventually be removed anyway.

**Comment by Modelmat** [comment]
Closing since #36 should have fixed this.
