### ISSUE TITLE
Automatically crop when exporting to PDF?

### ISSUE THREAD

**Issue by brechtm** [Modelmat/sphinxcontrib-drawio#31]
As far as I can tell, drawio crops the figure when exporting to formats other than PDF. It does offer the `--crop` command line option to also do this for PDF. Should we make use of it when exporting to PDF? I believe it makes sense to make this behavior consistent regardless of the output format (unlike drawio itself).

**Comment by brechtm** [comment]
Note that currently, `--scale 1` breaks `--crop`(https://github.com/jgraph/drawio-desktop/issues/344).

**Comment by ItayZiv** [comment]
This is something I looked into having as a feature, I never got to it, mainly because regardless this extension cannot work in an environment like RTD, and with other solutions like editable SVGs being around (which you can natively export from draw.io), adding such major features didn't seem like something super important.

**Comment by brechtm** [comment]
At the company I'm currently working for, we need to export to multiple formats (for HTML and PDF output), so saving an editable SVG will not work. Since we'll be using this extension heavily, I'm planning on fixing this issue and implementing some additional features, such as making the _drawio_ directive compatible with the _figure_ directive.

Can you shed some light on the status of sphinxcontrib-drawio? It's no longer actively developed but still receiving basic maintenance updates? Will you be accepting PRs? Would you like to discuss before I start implementing a feature?

**Comment by Modelmat** [comment]
It's no longer actively developed as it was initially developed for a project that couldn't use it, so we switched to editable PNGs.

Since I'm not actively testing it, I doubt it will be "maintained" although I will try to fix it if it breaks.

I'm happy to accept PRs. If you think a feature is worth implementing, go for it - I'm not opposed to the addition of any features into this extension.

If you have a question with a bit of code, contact Itay or I or just open an issue, I don't mind really.



The draw.io desktop app has quite a few things that don't work together / act as expected (as you've already seen), so expect to have fun with that.

As a general rule, please update documentation if you add a new feature.

If you'd like to add versioning guarantees (e.g. follow semver) that's also fine - at the moment this is still in "beta" and I don't know of anyone who actively uses this (please correct me if I'm wrong) so change whatever.
