### ISSUE TITLE
Figure out why pypi releases do the release but then fail

### ISSUE THREAD

**Issue by modelmat** [modelmat/sphinxcontrib-drawio#73]
It seems to be uploading the release twice? No idea why

**Comment by Milacus** [comment]
Maybe this helps to analyze the problem
* https://packaging.python.org/en/latest/guides/using-testpypi/
* https://github.com/pypa/gh-action-pypi-publish#advanced-release-management

**Comment by jdillard** [comment]
I'm not sure, but my guess is it is related to the triggers:

https://github.com/modelmat/sphinxcontrib-drawio/blob/373b54f179b19a0a6dee2493e9333811869210cb/.github/workflows/workflow.yml#L2-L13

Because the workflow sometimes runs several times for single commit, for example when I pushed and tagged https://github.com/modelmat/sphinxcontrib-drawio/commit/373b54f179b19a0a6dee2493e9333811869210cb:

![image](https://github.com/modelmat/sphinxcontrib-drawio/assets/3474095/b202f609-fd82-404b-b446-3934070ba78b)
source: https://github.com/modelmat/sphinxcontrib-drawio/actions
